#!/usr/bin/env python

import datetime, Queue, select, sys, threading, time

__version__ = "0.1.0"

def main(mode, update_rate, threshold_rate, window_seconds):
    threshold_events = EventStream()
    rate_events = EventStream()
    writer_input = rate_events if mode == 'guage' else threshold_events
    writer = threading.Thread(target=write, args=[writer_input])
    writer.daemon = True
    writer.start()

    if mode == 'threshold':
        thresholder = threading.Thread(target=threshold, args=[rate_events, threshold_events, threshold_rate])
        thresholder.daemon = True
        thresholder.start()

    input_events = EventStream()
    summarizer = threading.Thread(target=summarize, args=[input_events, rate_events, window_seconds])
    summarizer.daemon = True
    summarizer.start()

    clock = threading.Thread(target=tick, args=[input_events, update_rate])
    clock.daemon = True
    clock.start()

    reader = threading.Thread(target=timestamp_inputs, args=[input_events])
    reader.start()
    reader.join()

class EventStream:
    def __init__(self):
        self._message_queue = Queue.Queue()
        self._handlers = {}
        self._running = False

    def emit(self, name, data):
        self._message_queue.put((name, data))

    def on(self, name, handler):
        if name in self._handlers:
            self._handlers[name].append(handler)
        else:
            self._handlers[name] = [handler]

    def run(self):
        while True:
            message, data = self._message_queue.get()
            if message is None:
                break
            if message in self._handlers:
                for handler in self._handlers[message]:
                    handler(data)

    def quit(self):
        self.emit(None, None)

def timestamp_inputs(output):
    while sys.stdin in select.select([sys.stdin], [], [])[0]:
        line = sys.stdin.readline()
        if not line:
            output.quit()
            return
        now = datetime.datetime.utcnow()
        output.emit("line", now)

def tick(output, period):
    while True:
        time.sleep(period)
        output.emit("tick", period)

def summarize(input_, output, window):
    class Summarizer:
        def __init__(self, output, window):
            self._times = []
            self._window = window
            self._output = output

        def save_time(self, time):
            self._times.append(time)

        def send_summary(self, _):
            now = datetime.datetime.utcnow()
            self._times = [t for t in self._times if now - datetime.timedelta(seconds=self._window) < t]
            self._output.emit("rate", len(self._times) / float(self._window))

    s = Summarizer(output, window)
    input_.on("line", s.save_time)
    input_.on("tick", s.send_summary)
    input_.run()

def threshold(input_, output, threshold):
    class Thresholder:
        def __init__(self, output, threshold):
            self._threshold = threshold 
            self._rate = 0
            self._output = output

        def rate(self, current_rate):
            if self._rate < self._threshold <= current_rate:
                self._output.emit("threshold.above", current_rate)
            elif current_rate < self._threshold <= self._rate:
                self._output.emit("threshold.below", current_rate)
            self._rate = current_rate
    t = Thresholder(output, threshold)
    input_.on("rate", t.rate)
    input_.run()

def write(input_):
    def rate(rate):
        print rate
    def above_threshold(rate):
        print "rose above threshold at", datetime.datetime.now()
    def below_threshold(rate):
        print "fell below threshold at", datetime.datetime.now()
    input_.on("rate", rate)
    input_.on("threshold.above", above_threshold)
    input_.on("threshold.below", below_threshold)
    input_.run()

def parse_args(args):
    options = {
        'guage': False,
        'threshold': False,
        '--interval': 1,
        '--window': 3,
        '<rate>': None
    }
    expecting_argument = ''
    for arg in args:
        if expecting_argument:
            if expecting_argument == '--interval':
                options['--interval'] = float(arg)
            elif expecting_argument == '--window':
                options['--window'] = float(arg)
            expecting_argument = ''
        elif arg in ('-n', '--interval'):
            expecting_argument = '--interval'
        elif arg in ('-w', '--window'):
            expecting_argument = '--window'
        elif arg == 'guage':
            options['guage'] = True
        elif arg == 'threshold':
            options['threshold'] = True
        else:
            options['<rate>'] = float(arg)
    both_guage_and_threshold = options['guage'] and options['threshold']
    neither_guage_nor_threshold = not (options['guage'] or options['threshold'])
    rate_specified_for_guage = options['guage'] and options['<rate>']
    no_rate_for_threshold = options['threshold'] and not options['<rate>']
    if both_guage_and_threshold or neither_guage_nor_threshold or rate_specified_for_guage or no_rate_for_threshold:
        print_usage()
        sys.exit(1)
    return options

def print_usage():
    sys.stderr.write("""Usage:

  %s guage [--interval <interval>]
  %s threshold <rate> [--interval <interval>]

Measure the flow of data through a pipe.

Flags:
-n --interval  How frequently to recalculate the current rate. Default 1.
-w --window    The period of time to look at to calculate the current rate. Default 3.
""" % (sys.argv[0], sys.argv[0]))

if __name__ == '__main__':
    options = parse_args(sys.argv[1:])
    try:
        main('guage' if options['guage'] else 'threshold', options['--interval'], options['<rate>'], options['--window'])
    except KeyboardInterrupt:
        pass
